### ISSUE TITLE
Add a prefix to the hex package name

### ISSUE THREAD

**Issue by norbajunior** [betrybe/plug-mime-type-check#1]
@eucleciojosias There is the [Naming your package](https://hex.pm/docs/publish#naming-your-package) section in hex docs which says:

> If you are providing functionality on top of an existing package, consider using that package name as a prefix. For example, if you want to add authentication to [Plug](https://github.com/elixir-lang/plug), consider calling your package plug_auth (or plug_somename) instead of auth (or somename).

Based on that I'd recommend rename the package to `plug_mime_type_check`.

What do you think?

**Comment by LeandroLM** [comment]
@norbajunior @eucleciojosias  this package also depends directly on Phoenix, and Phoenix already depends on Plug, so maybe something like `phoenix_mime_type_check` would be more appropriate?

**Comment by norbajunior** [comment]
@LeandroLM actually this package doesn't need to depend on Phoenix. I opened a PR here removing it. https://github.com/betrybe/plug-mime-type-check/pull/2
